server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: C:/Users/heyin/IdeaProjects/Leyou-E-commerce/leyou/rsakey/rsa.pub # 公钥地址
    cookieName: USER_TOKEN # cookie的名称